service:
  name: menu-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: sa-east-1

functions:
  hello:
    handler: src/handlers/getMenu.handler
    events:
      - http:
          method: GET
          cors: true
          path: /cardapio/{campus}
