service: menu-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  stage: v2
  region: sa-east-1
  timeout: 30

functions:
  getMenuOfTheDay:
    handler: src/endpoints/getMenuOfTheDay.handler
    events:
      - http:
          method: GET
          path: /menu
  sendLunchMessageToGroup:
    handler: src/endpoints/scheduleEvent.handler
    events:
      - http:
          method: POST
          path: /message/almoco
      - schedule:
          rate:
            - cron(30 10 * * ? *)
          enabled: true
          input:
            dish: almoco
  sendDinnerMessageToGroup:
    handler: src/endpoints/scheduleEvent.handler
    events:
      - http:
          method: POST
          path: /message/jantar
      - schedule:
          rate:
            - cron(0 16 * * ? *)
          enabled: true
          input:
            dish: jantar

custom:
  bundle:
    linting: false
