service: menu-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: v2
  region: sa-east-1

functions:
  hello:
    handler: src/handlers/getMenuOfTheDay.handler
    events:
      - http:
          method: GET
          path: /menu

custom:
  bundle:
    linting: false
